//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoRatChat.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwoRatChat.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply (reload) skin:.
        /// </summary>
        public static string BUT_ApplySkin {
            get {
                return ResourceManager.GetString("BUT_ApplySkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add chat source....
        /// </summary>
        public static string cxt_AddChatSource {
            get {
                return ResourceManager.GetString("cxt_AddChatSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show blacklist editor....
        /// </summary>
        public static string cxt_Blacklist {
            get {
                return ResourceManager.GetString("cxt_Blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cxt_CancelMenu {
            get {
                return ResourceManager.GetString("cxt_CancelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close TwoRatChat.
        /// </summary>
        public static string cxt_Close {
            get {
                return ResourceManager.GetString("cxt_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close chat source.
        /// </summary>
        public static string cxt_CloseChat {
            get {
                return ResourceManager.GetString("cxt_CloseChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command editor....
        /// </summary>
        public static string cxt_CommandEditor {
            get {
                return ResourceManager.GetString("cxt_CommandEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База данных зрителей....
        /// </summary>
        public static string cxt_CustomUsers {
            get {
                return ResourceManager.GetString("cxt_CustomUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show fortune ring editor....
        /// </summary>
        public static string cxt_Fortunering {
            get {
                return ResourceManager.GetString("cxt_Fortunering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show options....
        /// </summary>
        public static string cxt_Options {
            get {
                return ResourceManager.GetString("cxt_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show poll editor....
        /// </summary>
        public static string cxt_Polleditor {
            get {
                return ResourceManager.GetString("cxt_Polleditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload chat.
        /// </summary>
        public static string cxt_ReloadChat {
            get {
                return ResourceManager.GetString("cxt_ReloadChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset chat window position.
        /// </summary>
        public static string cxt_ResetPosition {
            get {
                return ResourceManager.GetString("cxt_ResetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open skin designer....
        /// </summary>
        public static string cxt_SkinDesigner {
            get {
                return ResourceManager.GetString("cxt_SkinDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string dbt_cancel {
            get {
                return ResourceManager.GetString("dbt_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string dbt_ok {
            get {
                return ResourceManager.GetString("dbt_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat source:.
        /// </summary>
        public static string dtb_ChatSource {
            get {
                return ResourceManager.GetString("dtb_ChatSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 001: Channel not found..
        /// </summary>
        public static string ERROR_001 {
            get {
                return ResourceManager.GetString("ERROR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 002: Site API was changed..
        /// </summary>
        public static string ERROR_002 {
            get {
                return ResourceManager.GetString("ERROR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли и логины хранятся с минимальным шифрованием на жестком диске (в файле настройки). Хранить их тут небезопасно!.
        /// </summary>
        public static string MES_BotWarning {
            get {
                return ResourceManager.GetString("MES_BotWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream channel or ID:.
        /// </summary>
        public static string MES_ChannelOrID {
            get {
                return ResourceManager.GetString("MES_ChannelOrID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Message deleted&gt;.
        /// </summary>
        public static string MES_Deleted {
            get {
                return ResourceManager.GetString("MES_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error, please restart program..
        /// </summary>
        public static string MES_FatalError {
            get {
                return ResourceManager.GetString("MES_FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow GG animated smiles (reload required):.
        /// </summary>
        public static string MES_GGAllowAnimated {
            get {
                return ResourceManager.GetString("MES_GGAllowAnimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow GG premium smiles (reload required):.
        /// </summary>
        public static string MES_GGAllowChannel {
            get {
                return ResourceManager.GetString("MES_GGAllowChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable server.
        /// </summary>
        public static string MES_HttpEnable {
            get {
                return ResourceManager.GetString("MES_HttpEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http listen uri (reload required):.
        /// </summary>
        public static string MES_HttpListen {
            get {
                return ResourceManager.GetString("MES_HttpListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube video ID:.
        /// </summary>
        public static string MES_Id {
            get {
                return ResourceManager.GetString("MES_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat label:.
        /// </summary>
        public static string MES_Label {
            get {
                return ResourceManager.GetString("MES_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoRatChat options..
        /// </summary>
        public static string MES_Options {
            get {
                return ResourceManager.GetString("MES_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streamer nick:.
        /// </summary>
        public static string MES_Streamer {
            get {
                return ResourceManager.GetString("MES_Streamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streamer nick or ID:.
        /// </summary>
        public static string MES_StreamerOrID {
            get {
                return ResourceManager.GetString("MES_StreamerOrID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streamer ID:.
        /// </summary>
        public static string MES_StrId {
            get {
                return ResourceManager.GetString("MES_StrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! Do not change this urls by yourself. After changes reboot required!.
        /// </summary>
        public static string MES_UrlWarning {
            get {
                return ResourceManager.GetString("MES_UrlWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} стал новым фолловером!.
        /// </summary>
        public static string NewFollowerMessage {
            get {
                return ResourceManager.GetString("NewFollowerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color:.
        /// </summary>
        public static string OPT_AccentColor {
            get {
                return ResourceManager.GetString("OPT_AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow hitbox colors (only new messages):.
        /// </summary>
        public static string OPT_AllowHitboxColors {
            get {
                return ResourceManager.GetString("OPT_AllowHitboxColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow leveling (only new messages):.
        /// </summary>
        public static string OPT_AllowLeveling {
            get {
                return ResourceManager.GetString("OPT_AllowLeveling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color:.
        /// </summary>
        public static string OPT_BackColor {
            get {
                return ResourceManager.GetString("OPT_BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show border:.
        /// </summary>
        public static string OPT_Border {
            get {
                return ResourceManager.GetString("OPT_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow check twitch followers:.
        /// </summary>
        public static string OPT_CheckFollowers {
            get {
                return ResourceManager.GetString("OPT_CheckFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable full window dragging:.
        /// </summary>
        public static string OPT_DisableFullDrag {
            get {
                return ResourceManager.GetString("OPT_DisableFullDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download history:.
        /// </summary>
        public static string OPT_DowloadHistory {
            get {
                return ResourceManager.GetString("OPT_DowloadHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &quot;new follower&quot; message in chat:.
        /// </summary>
        public static string OPT_FollowersInChat {
            get {
                return ResourceManager.GetString("OPT_FollowersInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodgame header mode:.
        /// </summary>
        public static string OPT_GGHeaderMode {
            get {
                return ResourceManager.GetString("OPT_GGHeaderMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save chat as image (*.png):.
        /// </summary>
        public static string OPT_ImagePath {
            get {
                return ResourceManager.GetString("OPT_ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max image size:.
        /// </summary>
        public static string OPT_MaxImageSize {
            get {
                return ResourceManager.GetString("OPT_MaxImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is window mouse transparent:.
        /// </summary>
        public static string OPT_MouseTransparent {
            get {
                return ResourceManager.GetString("OPT_MouseTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable overlay mode (reload required):.
        /// </summary>
        public static string OPT_OverlayMode {
            get {
                return ResourceManager.GetString("OPT_OverlayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Sometime OBS or XSplit require to this option).
        /// </summary>
        public static string OPT_OverlayMode2 {
            get {
                return ResourceManager.GetString("OPT_OverlayMode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate command on first message:.
        /// </summary>
        public static string OPT_PlaySoundOnFirstMessage {
            get {
                return ResourceManager.GetString("OPT_PlaySoundOnFirstMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show images from:.
        /// </summary>
        public static string OPT_ShowImagesFrom {
            get {
                return ResourceManager.GetString("OPT_ShowImagesFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show button in taskbar (EXPERIMENTAL):.
        /// </summary>
        public static string OPT_ShowInTaskbar {
            get {
                return ResourceManager.GetString("OPT_ShowInTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show twitch subscriber icon (reload required):.
        /// </summary>
        public static string OPT_ShowTwitchSubsIcon {
            get {
                return ResourceManager.GetString("OPT_ShowTwitchSubsIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show images from urls:.
        /// </summary>
        public static string OPT_ShowUrlsAsImages {
            get {
                return ResourceManager.GetString("OPT_ShowUrlsAsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat root html (skin):.
        /// </summary>
        public static string OPT_Skin {
            get {
                return ResourceManager.GetString("OPT_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top:.
        /// </summary>
        public static string OPT_TopMost {
            get {
                return ResourceManager.GetString("OPT_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow twitch colors (only new messages):.
        /// </summary>
        public static string OPT_UseColors {
            get {
                return ResourceManager.GetString("OPT_UseColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст с вопросом:.
        /// </summary>
        public static string OPT_voice_ask {
            get {
                return ResourceManager.GetString("OPT_voice_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восклицание:.
        /// </summary>
        public static string OPT_voice_caps {
            get {
                return ResourceManager.GetString("OPT_voice_caps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice on first message (clear to silence):.
        /// </summary>
        public static string OPT_voice_FirstMeet {
            get {
                return ResourceManager.GetString("OPT_voice_FirstMeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice on follower (clear to silence):.
        /// </summary>
        public static string OPT_voice_Followers {
            get {
                return ResourceManager.GetString("OPT_voice_Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom voice for viewers (require restart):.
        /// </summary>
        public static string OPT_voice_Personals {
            get {
                return ResourceManager.GetString("OPT_voice_Personals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice on promoute message (clear to silence):.
        /// </summary>
        public static string OPT_voice_Promoute {
            get {
                return ResourceManager.GetString("OPT_voice_Promoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обычный текст:.
        /// </summary>
        public static string OPT_voice_talk {
            get {
                return ResourceManager.GetString("OPT_voice_talk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Youtube API KEY:.
        /// </summary>
        public static string OPT_YoutubeAPIKey {
            get {
                return ResourceManager.GetString("OPT_YoutubeAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show youtube user icon:.
        /// </summary>
        public static string OPT_YoutubeIcon {
            get {
                return ResourceManager.GetString("OPT_YoutubeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TAB_About {
            get {
                return ResourceManager.GetString("TAB_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awards.
        /// </summary>
        public static string TAB_Awards {
            get {
                return ResourceManager.GetString("TAB_Awards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot.
        /// </summary>
        public static string TAB_Bot {
            get {
                return ResourceManager.GetString("TAB_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string TAB_Main {
            get {
                return ResourceManager.GetString("TAB_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat urls.
        /// </summary>
        public static string TAB_Urls {
            get {
                return ResourceManager.GetString("TAB_Urls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        public static string TAB_Voice {
            get {
                return ResourceManager.GetString("TAB_Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Enter here &apos;pick phrase&apos; to select brave from chat..
        /// </summary>
        public static string tip_FRPhrase {
            get {
                return ResourceManager.GetString("tip_FRPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Seconds before select..
        /// </summary>
        public static string tip_FRSeconds {
            get {
                return ResourceManager.GetString("tip_FRSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Winners count (default 1)..
        /// </summary>
        public static string tip_FRWinners {
            get {
                return ResourceManager.GetString("tip_FRWinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во зрителей/кол-во людей в чате/Позиция среди стримов (меньше - лучше).
        /// </summary>
        public static string tip_goodGameTooltip {
            get {
                return ResourceManager.GetString("tip_goodGameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user change choice:.
        /// </summary>
        public static string tip_PollAllowChange {
            get {
                return ResourceManager.GetString("tip_PollAllowChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user remove choice:.
        /// </summary>
        public static string tip_PollAllowRemove {
            get {
                return ResourceManager.GetString("tip_PollAllowRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to TwoRatChat.
        ///Please, press the right mouse button to add chat source..
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
