//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoRatChat.Main.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Upgraded {
            get {
                return ((bool)(this["Upgraded"]));
            }
            set {
                this["Upgraded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Window_X {
            get {
                return ((double)(this["Window_X"]));
            }
            set {
                this["Window_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Window_Y {
            get {
                return ((double)(this["Window_Y"]));
            }
            set {
                this["Window_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double Window_Width {
            get {
                return ((double)(this["Window_Width"]));
            }
            set {
                this["Window_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double Window_Height {
            get {
                return ((double)(this["Window_Height"]));
            }
            set {
                this["Window_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Window_OverlayMode {
            get {
                return ((bool)(this["Window_OverlayMode"]));
            }
            set {
                this["Window_OverlayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_TopMost {
            get {
                return ((bool)(this["Window_TopMost"]));
            }
            set {
                this["Window_TopMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Window_ShowHeader {
            get {
                return ((bool)(this["Window_ShowHeader"]));
            }
            set {
                this["Window_ShowHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_DisableFullDrag {
            get {
                return ((bool)(this["Window_DisableFullDrag"]));
            }
            set {
                this["Window_DisableFullDrag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ws://chat.goodgame.ru:8081/chat/websocket|ws://goodgame.ru:8081/chat/websocket")]
        public string url_Goodgame {
            get {
                return ((string)(this["url_Goodgame"]));
            }
            set {
                this["url_Goodgame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Chat_LoadHistory {
            get {
                return ((bool)(this["Chat_LoadHistory"]));
            }
            set {
                this["Chat_LoadHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChatSave {
            get {
                return ((string)(this["ChatSave"]));
            }
            set {
                this["ChatSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4283925199")]
        public uint Window_AccentColor {
            get {
                return ((uint)(this["Window_AccentColor"]));
            }
            set {
                this["Window_AccentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Window_Border {
            get {
                return ((bool)(this["Window_Border"]));
            }
            set {
                this["Window_Border"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("570425344")]
        public uint Window_BackgroundColor {
            get {
                return ((uint)(this["Window_BackgroundColor"]));
            }
            set {
                this["Window_BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("irc.twitch.tv:6667")]
        public string url_Twitch {
            get {
                return ((string)(this["url_Twitch"]));
            }
            set {
                this["url_Twitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/default.html")]
        public string Chat_RootSkin {
            get {
                return ((string)(this["Chat_RootSkin"]));
            }
            set {
                this["Chat_RootSkin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Chat_ImagePath {
            get {
                return ((string)(this["Chat_ImagePath"]));
            }
            set {
                this["Chat_ImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ws://cybergame.tv:9090/websocket")]
        public string url_Cybergame {
            get {
                return ((string)(this["url_Cybergame"]));
            }
            set {
                this["url_Cybergame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_MouseTransparent {
            get {
                return ((bool)(this["Window_MouseTransparent"]));
            }
            set {
                this["Window_MouseTransparent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int sc2tv_lastCount {
            get {
                return ((int)(this["sc2tv_lastCount"]));
            }
            set {
                this["sc2tv_lastCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://chat.sc2tv.ru/memfs/channel-{0}.json")]
        public string url_Sc2tv {
            get {
                return ((string)(this["url_Sc2tv"]));
            }
            set {
                this["url_Sc2tv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.empiretv.org/sites/default/files/fastchat/chat{0}.json?{1}")]
        public string url_Empire {
            get {
                return ((string)(this["url_Empire"]));
            }
            set {
                this["url_Empire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("i.gohanet.ru:6667")]
        public string url_GohaTV {
            get {
                return ((string)(this["url_GohaTV"]));
            }
            set {
                this["url_GohaTV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("midlane.ru:7070")]
        public string url_midlane {
            get {
                return ((string)(this["url_midlane"]));
            }
            set {
                this["url_midlane"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gamerstv.ru/modules/ajax/chat_cache/room_{0}.js")]
        public string url_GamersTV {
            get {
                return ((string)(this["url_GamersTV"]));
            }
            set {
                this["url_GamersTV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:2222/")]
        public string HTTP_ListenUri {
            get {
                return ((string)(this["HTTP_ListenUri"]));
            }
            set {
                this["HTTP_ListenUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HTTP_Enable {
            get {
                return ((bool)(this["HTTP_Enable"]));
            }
            set {
                this["HTTP_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3•obmorok•")]
        public string Chat_Blacklist {
            get {
                return ((string)(this["Chat_Blacklist"]));
            }
            set {
                this["Chat_Blacklist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GG_AllowAnimatedSmiles {
            get {
                return ((bool)(this["GG_AllowAnimatedSmiles"]));
            }
            set {
                this["GG_AllowAnimatedSmiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GG_AllowChannelSmiles {
            get {
                return ((bool)(this["GG_AllowChannelSmiles"]));
            }
            set {
                this["GG_AllowChannelSmiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableGlobalHoyKeys {
            get {
                return ((bool)(this["EnableGlobalHoyKeys"]));
            }
            set {
                this["EnableGlobalHoyKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double GlobalVolume {
            get {
                return ((double)(this["GlobalVolume"]));
            }
            set {
                this["GlobalVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool twitch_ShowSubsIcon {
            get {
                return ((bool)(this["twitch_ShowSubsIcon"]));
            }
            set {
                this["twitch_ShowSubsIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool twitch_AllowUseColors {
            get {
                return ((bool)(this["twitch_AllowUseColors"]));
            }
            set {
                this["twitch_AllowUseColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hitbox_AllowUserColors {
            get {
                return ((bool)(this["hitbox_AllowUserColors"]));
            }
            set {
                this["hitbox_AllowUserColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bot_GGLogin {
            get {
                return ((string)(this["bot_GGLogin"]));
            }
            set {
                this["bot_GGLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bot_GGPass {
            get {
                return ((string)(this["bot_GGPass"]));
            }
            set {
                this["bot_GGPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bot_TwitchLogin {
            get {
                return ((string)(this["bot_TwitchLogin"]));
            }
            set {
                this["bot_TwitchLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bot_TwitchPass {
            get {
                return ((string)(this["bot_TwitchPass"]));
            }
            set {
                this["bot_TwitchPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool newFollowerShowInChat {
            get {
                return ((bool)(this["newFollowerShowInChat"]));
            }
            set {
                this["newFollowerShowInChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int gg_HeaderMode {
            get {
                return ((int)(this["gg_HeaderMode"]));
            }
            set {
                this["gg_HeaderMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool twitch_Followers {
            get {
                return ((bool)(this["twitch_Followers"]));
            }
            set {
                this["twitch_Followers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} получил новый уровень. Теперь он {1}.")]
        public string promouteMessage {
            get {
                return ((string)(this["promouteMessage"]));
            }
            set {
                this["promouteMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool allowLeveling {
            get {
                return ((bool)(this["allowLeveling"]));
            }
            set {
                this["allowLeveling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string soundOnMessage {
            get {
                return ((string)(this["soundOnMessage"]));
            }
            set {
                this["soundOnMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool youtube_ShowIcons {
            get {
                return ((bool)(this["youtube_ShowIcons"]));
            }
            set {
                this["youtube_ShowIcons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} готов к геноциду!")]
        public string voice_FirstMeet {
            get {
                return ((string)(this["voice_FirstMeet"]));
            }
            set {
                this["voice_FirstMeet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} получил новый уровень. Теперь он {1}.")]
        public string voice_Promoute {
            get {
                return ((string)(this["voice_Promoute"]));
            }
            set {
                this["voice_Promoute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} при соединился к команде крысоидов!")]
        public string voice_Followers {
            get {
                return ((string)(this["voice_Followers"]));
            }
            set {
                this["voice_Followers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string voice_Personals {
            get {
                return ((string)(this["voice_Personals"]));
            }
            set {
                this["voice_Personals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://streamcube.tv/{0}")]
        public string url_StreamCube {
            get {
                return ((string)(this["url_StreamCube"]));
            }
            set {
                this["url_StreamCube"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showUrlsAsImages {
            get {
                return ((bool)(this["showUrlsAsImages"]));
            }
            set {
                this["showUrlsAsImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("320")]
        public int maxImageWidth {
            get {
                return ((int)(this["maxImageWidth"]));
            }
            set {
                this["maxImageWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int maxImageHeight {
            get {
                return ((int)(this["maxImageHeight"]));
            }
            set {
                this["maxImageHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int showImageMode {
            get {
                return ((int)(this["showImageMode"]));
            }
            set {
                this["showImageMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string imageWhiteList {
            get {
                return ((string)(this["imageWhiteList"]));
            }
            set {
                this["imageWhiteList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string imageBlackList {
            get {
                return ((string)(this["imageBlackList"]));
            }
            set {
                this["imageBlackList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowInTaskbar {
            get {
                return ((bool)(this["ShowInTaskbar"]));
            }
            set {
                this["ShowInTaskbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wss://chat.funstream.tv")]
        public string peka2tv_chatUrl {
            get {
                return ((string)(this["peka2tv_chatUrl"]));
            }
            set {
                this["peka2tv_chatUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IVONA 2 Tatyana")]
        public string voice_voiceId {
            get {
                return ((string)(this["voice_voiceId"]));
            }
            set {
                this["voice_voiceId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string youTubeAPIKey {
            get {
                return ((string)(this["youTubeAPIKey"]));
            }
            set {
                this["youTubeAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} спрашивает: \'{1}\'")]
        public string voice_ask {
            get {
                return ((string)(this["voice_ask"]));
            }
            set {
                this["voice_ask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} говорит: \'{1}\'")]
        public string voice_talk {
            get {
                return ((string)(this["voice_talk"]));
            }
            set {
                this["voice_talk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} восклицает: \'{1}\'")]
        public string voice_caps {
            get {
                return ((string)(this["voice_caps"]));
            }
            set {
                this["voice_caps"] = value;
            }
        }
    }
}
